channels: !!python/tuple
- au-eoed
- defaults
- conda-forge
dependencies:
- curl=7.49.0=1
- gdal=2.1.0=py35_0
- geos=3.5.0=0
- geotiff=1.4.1=0
- hdf4=4.2.12=0
- hdf5=1.8.17=1
- jbig=2.1=0
- jpeg=8d=2
- kealib=1.4.6=0
- libgdal=2.1.0=0
- libgfortran=3.0.0=1
- libnetcdf=4.4.1=0
- libtiff=4.0.6=2
- mkl=11.3.3=0
- numpy=1.11.2=py35_0
- openssl=1.0.2j=0
- pip=9.0.1=py35_1
- proj4=4.9.2=0
- pyproj=1.9.5.1=py35_0
- python=3.5.2=0
- readline=6.2=2
- scipy=0.18.1=np111py35_0
- setuptools=27.2.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xerces-c=3.1.4=0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - ferretmagic==1.2
  - gcircle==0.0.1
  - pipedviewer==1.3.0
  - pyferret==1.2

